Repository tpambor/MISW4203-Vinilos-App, pull requests merged in 2023-12, with the labels that each got.

#181 Creación álbum
  app/build.gradle.kts
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumCreateTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/AlbumCreate.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/AlbumList.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/AlbumDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/AlbumRequestJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/AlbumRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/MainActivity.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/AlbumCreateViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumCreateScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/Navigation.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumCommentViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumCreateViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumTrackViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/NetworkServiceAdapterTest.kt
  app/src/test/resources/addAlbum.json
Labels: HU07

#183 Micro-optimización: Evitar la creación de objetos innecesarios
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/AlbumRepository.kt
Labels: optimization

#184 Bugfix: Fechas no tienen zona horaria
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistDetailScreen.kt
Labels: bug

#187 Optimización: Simplificar estrategia de caché
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/ArtistDetail.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/VinilosDB.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/CacheDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/Cache.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/AlbumRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/CollectorRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/AlbumListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/CollectorListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/PerformerListViewModel.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumCommentViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumCreateViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumTrackViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/ArtistAddAlbumViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/BandAddMusicianViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/BandViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/MusicianViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
Labels: optimization

#185 Bugfix: Usuario también puede actualizar la lista cuando está vacía
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/CollectorListScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug

#188 Llamar onRefreshMusicians() en getMusicians()
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/PerformerListViewModel.kt
Labels: bug
