Repository tpambor/MISW4203-Vinilos-App, pull requests merged in 2023-11, with the labels that each got.

#99 HU03: Consultar el listado de artistas
  app/build.gradle.kts
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumListTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/ArtistListTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/ArtistList.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/NavBar.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/PageObject.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/Album.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/Band.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/Converters.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/Musician.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/Performer.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/PerformerDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/VinilosDB.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/network/InstantAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/network/PerformerAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/viewmodels/PerformerListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/views/ArtistListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/views/Navigation.kt
  app/src/main/res/drawable/ic_collector_24.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/ConvertersTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/NetworkServiceAdapterTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
  app/src/test/resources/bands.json
  app/src/test/resources/musicians.json
Labels: HU03

#105 Album and Artists empty list message
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/views/ArtistListScreen.kt
  app/src/main/res/values/strings.xml
Labels: bug, HU01, HU03

#104 Album and Artists list ordered
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/AlbumDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/PerformerDAO.kt
Labels: bug, HU01, HU03

#109 Fix: Muestra artistas favoritas en el listado de músicos y bandas
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/models/PerformerDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/viewmodels/PerformerListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/views/ArtistListScreen.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
Labels: HU03

#115 Actualizar versiones de librerías
  .idea/kotlinc.xml
  app/build.gradle.kts
  build.gradle.kts
  libraries/androidx-compose-material3-pullrefresh/library/local.properties
Labels: optimization

#116 Refactor: Usar Result<T> en repositories en lugar de null
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/AlbumRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/CollectorRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/AlbumListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/CollectorListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/PerformerListViewModel.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
Labels: optimization

#117 Micro optimizaciones
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/ArtistList.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/CollectorList.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/theme/Color.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/ErrorUiState.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/UserViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/CollectorListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/Navigation.kt
  app/src/main/res/drawable-mdpi/ic_vinilos.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/xml/data_extraction_rules.xml
Labels: optimization

#119 HU10: Agregar artistas favoritos
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/ArtistListTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/ArtistItem.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/ArtistList.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/CollectorDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/PerformerDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/HttpRequestQueue.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/BandJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/CollectorJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/MusicianJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/PerformerListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistListScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/NetworkServiceAdapterTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
  app/src/test/resources/addFavoriteBand.json
  app/src/test/resources/addFavoriteMusician.json
  app/src/test/resources/bands.json
  app/src/test/resources/musicians.json
Labels: HU10

#128 HU04: Consultar la información detallada de un artista
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/ArtistDetailTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/ArtistDetail.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/VinilosDB.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/AlbumDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/PerformerDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/MusicianBand.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/PerformerAlbum.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/MainActivity.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/BandViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/MusicianViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/PerformerViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/Navigation.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/BandViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/MusicianViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/NetworkServiceAdapterTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
  app/src/test/resources/band.json
  app/src/test/resources/musician.json
Labels: HU04

#131 Optimización: Trabajar en hilos IO
  app/build.gradle.kts
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/AlbumListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/BandViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/CollectorListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/MusicianViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/PerformerListViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/PerformerViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/UserViewModel.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/AlbumListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/BandViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/MusicianViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/UserViewModelTest.kt
  build.gradle.kts
  libraries/androidx-compose-material3-pullrefresh/library/local.properties
Labels: optimization

#137 Bugfix/navegacion
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/Navigation.kt
Labels: bug

#155 HU06: Consultar la información detallada de coleccionista
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorDetailTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/CollectorDetail.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/JsonAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/VinilosDB.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/CollectorDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/CollectorAlbum.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/CollectorAlbumCrossRef.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/CollectorAlbumStatus.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/CollectorAlbumJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/CollectorJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/CollectorRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/CollectorViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/CollectorDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/CollectorListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/Navigation.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/NetworkServiceAdapterTest.kt
  app/src/test/resources/collector.json
  app/src/test/resources/collectors.json
Labels: HU06

#156 Release Sprint3 avance
  app/build.gradle.kts
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorDetailTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/CollectorDetail.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/JsonAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/VinilosDB.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/CollectorDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/CollectorAlbum.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/CollectorAlbumCrossRef.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/models/CollectorAlbumStatus.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/CollectorAlbumJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/models/CollectorJson.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/CollectorRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/CollectorViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/CollectorDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/CollectorListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/Navigation.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorListViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/CollectorViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/NetworkServiceAdapterTest.kt
  app/src/test/resources/collector.json
  app/src/test/resources/collectors.json
  gradle.properties
Labels: HU06

#176 HU15: Agregar un álbum a un artista
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/ArtistAddAlbumTest.kt
  app/src/androidTest/java/co/edu/uniandes/misw4203/equipo11/vinilos/pageobjects/ArtistDetail.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/AlbumDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/database/daos/PerformerDAO.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/network/NetworkServiceAdapter.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/data/repositories/PerformerRepository.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/viewmodels/ArtistAddAlbumViewModel.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/AlbumListScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistAddAlbumScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/ArtistDetailScreen.kt
  app/src/main/java/co/edu/uniandes/misw4203/equipo11/vinilos/ui/views/Navigation.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/ArtistAddAlbumViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/BandAddMusicianViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/BandViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/MusicianViewModelTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/NetworkServiceAdapterTest.kt
  app/src/test/java/co/edu/uniandes/misw4203/equipo11/vinilos/PerformerListViewModelTest.kt
  app/src/test/resources/addBandToAlbum.json
  app/src/test/resources/addMusicianToAlbum.json
Labels: HU15
